apiVersion: tutorial.my.domain/v1
kind: Foo
metadata:
  labels:
    app.kubernetes.io/name: foo
    app.kubernetes.io/instance: foo-sample
    app.kubernetes.io/part-of: buildin10mins
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: buildin10mins
  name: foo-sample
spec:
  # TODO(user): Add fields here
